#pragma config(Sensor, S1,     son1,           sensorSONAR)
#pragma config(Sensor, S2,     cor,            sensorCOLORFULL)
#pragma config(Sensor, S3,     cor2,           sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	Sleep(5000);

	while(true)
	{
		int son1 = SensorValue[S1];
		int cor = SensorValue[S2];
		int cor2 = SensorValue[S3]
		if (son1<255)
		{
	  //if (cor == WHITECOLOR)
		//{
			// vai pra frente

			if(SensorValue[S2] == BLACKCOLOR)
			{
				motor[motorA] = -100;
				motor[motorC] = -100;
				Sleep(1000);
				motor[motorA] = 50;
				motor[motorC] = 0;
				Sleep(1000);
			/*		*/
			}
			else if (SensorValue[S3] == BLACKCOLOR)
			{
					motor[motorA] = 100;
					motor[motorC] = 100;
					Sleep(1000);
					motor[motorA] = 50;
					motor[motorC] = 0;
					Sleep(1000);

				//Sleep(1000);
			}
			else
			{
			motor[motorA] = -100;
			motor[motorC] = -100;
				// faz girar
				//motor[motorA] = 50;
				//motor[motorC] = 0;

				//Sleep(1000);
			}
		}else{
				motor[motorA] = 50;
				motor[motorC] = 0;
		}
		if(SensorValue[S2] == BLACKCOLOR)
		{

			motor[motorA] = -100;
			motor[motorC] = -100;
			Sleep(1000);
			motor[motorA] = 50;
			motor[motorC] = 0;
			Sleep(1000);
			if (SensorValue[S3] == BLACKCOLOR)
			{
				motor[motorA] = 100;
			motor[motorC] = 100;
			Sleep(1000);
			motor[motorA] = 50;
			motor[motorC] = 0;
			Sleep(1000);
		}

	 }
}
}
