#pragma config(Sensor, S1,     olhoD,          sensorSONAR)
#pragma config(Sensor, S2,     cor2,           sensorCOLORFULL)
#pragma config(Sensor, S3,     cor3,           sensorCOLORFULL)
#pragma config(Sensor, S4,     olhoE,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int dist = SensorValue[S3];

	Sleep(5000);

	while (true){

		if(SensorValue[S2] != BLACKCOLOR){
			motor[motorA] = -100;
			motor[motorC] = -100;
				sleep(2000);

		}else if(SensorValue[S2] == BLACKCOLOR){
			motor[motorA] = 50;
			motor[motorC] = 50;
				sleep(2000);
	}
		break;
	}

		while (true){
		motor[motorA] = -50;
		motor[motorB] = 50;

		if (SensorValue[S4]<250){
			motor[motorA] = 50;
			motor[motorC] = 50;
			Sleep(300);
			motor[motorA] = 50;
			motor[motorC] = 50;
			Sleep(100);
			motor[motorA] = 50;
			motor[motorC] = 50;


				if(SensorValue[S3] == BLACKCOLOR){
					motor[motorA] = -50;
					motor[motorC] = -50;
					Sleep(50);
				}
			}

		}

	}
